try:
    print(name)
except Exception as e:
    print("出现异常了")